### ISSUE TITLE
User management broken and Player without `displayName` shows `None` in lobby and profile

### ISSUE THREAD

**Issue by madfcat** [DaveeHorvath/ascension#104]
The user update and register was affected by `escape` from the latest XSS update. It should be fixed in the suggested PR.

It alse lead to the None in `username` for lobby for profile

<img width="764" alt="Screenshot 2024-12-30 at 14 36 39" src="https://github.com/user-attachments/assets/e1f15924-845c-4bcc-8862-ff462eb38c3b" />
<img width="612" alt="image" src="https://github.com/user-attachments/assets/f55a6b8e-c1f2-4341-aac5-2d1a9ac25a16" />

**Comment by nikkxll** [comment]
Pls check also #96 and #102
