### ISSUE TITLE
Bug: Random signup popup

### ISSUE THREAD

**Issue by madfcat** [DaveeHorvath/ascension#66]
To replicate:
- Signup
- Click "Profile"
- Click "Back to menu"

No neeed to change the name. And it does not matter if you enter display name or not while signing up.

https://github.com/user-attachments/assets/50ff212b-f0c2-4ce3-bf5f-f4cf3cb017e9

**Comment by nikkxll** [comment]
@DaveeHorvath could you check it? Looks like somewhat related to history

**Comment by madfcat** [comment]
We are about to fix it now. The history was not updating on "Sign up" button.
