### ISSUE TITLE
Tournament, Single game, 2x2 Game lobbies does not show display names and avatars

### ISSUE THREAD

**Issue by madfcat** [DaveeHorvath/ascension#75]
Tournament, Single Games, 2x2 Game lobbies should show display names and only fall back to usernames if there is not display name available.
It also does not show avatars.

**Comment by nikkxll** [comment]
should be fixed in my branch

**Comment by nikkxll** [comment]
Please consider closing the issue

**Comment by madfcat** [comment]
> Please consider closing the issue

Does it allow to close it from your side?
Closed.
