### ISSUE TITLE
Impossible to choose players for the second single game in a row

### ISSUE THREAD

**Issue by madfcat** [DaveeHorvath/ascension#77]
It is impossible to play 2 single games in a row.
https://github.com/user-attachments/assets/f8658580-22ef-4adb-a3a4-df519d461f0d

Breaks if you press Start Match:
https://github.com/user-attachments/assets/cbcf2aa2-905f-4a0e-a088-a3d5298b7d9e

After it breaks not possible to exit the game screen.
Pressing `back` in the browser makes things pop-up on top of the blank game window. (not shown on the video but you can experiment on your own)

**Comment by nikkxll** [comment]
Should be fixed in current master
Please, consider closing the issue
