### ISSUE TITLE
Creating game without choosing players after going back in browser

### ISSUE THREAD

**Issue by madfcat** [DaveeHorvath/ascension#79]
Replicate:
- Create a Single game
- Press `back` in browser
- Create another game

Now we do not know who we are playing for.

Btw, should we add names of the players in the game itself?

https://github.com/user-attachments/assets/20e4c110-add2-4ef6-a2b2-f34220ce8ffd

**Comment by dnapi** [comment]
The same  on nikkxll/profile-new-features. tested on Hive machine on Chome

**Comment by madfcat** [comment]
> The same on nikkxll/profile-new-features. tested on Hive machine on Chome

Yes, all the issues are still there.
