### ISSUE TITLE
AI: AI stopped playing in any game.

### ISSUE THREAD

**Issue by taoramo** [DaveeHorvath/ascension#86]
This happened with a non-fresh db. Steps to replicate:

-log in 4 users
-log out the 4th user
-create and play tournament

AI doesn't play in tournament or single game anymore as far as I can tell.

I'll see what exactly happens after deleting everything and starting fresh.

**Comment by taoramo** [comment]
Replicated with fresh db

**Comment by madfcat** [comment]
Let's check it out :)

**Comment by taoramo** [comment]
In this state with 3 players logged in I get a 400 "Sessions not verified" from /api/tournaments/1/matches

**Comment by madfcat** [comment]
> In this state with 3 players logged in I get a 400 "Sessions not verified" from /api/tournaments/1/matches

Have you tried to remove all the cookies from the browser?

**Comment by taoramo** [comment]
yes, tried with everything fresh

**Comment by taoramo** [comment]
seems like the ai player doesn't get reinstated somewhere after logging out the 4th user

**Comment by taoramo** [comment]
in this state I also get "Not enough players are logged in to finish the tournament" alert after single player game

**Comment by madfcat** [comment]
> This happened with a non-fresh db. Steps to replicate:
> 
> -log in 4 users -log out the 4th user -create and play tournament
> 
> AI doesn't play in tournament or single game anymore as far as I can tell.
> 
> I'll see what exactly happens after deleting everything and starting fresh.

Works for me as intended (master branch):

https://github.com/user-attachments/assets/47165bcb-fd2f-4ba3-bbdc-1ea21fbf97c3

The thing that does not work is that AI is not responding for the first ball. It is basically the only way to score in AI versus lol (at 3:12)

**Comment by taoramo** [comment]
only relevant difference I can think of between your demo and my case is that one of the users was 42auth

https://github.com/user-attachments/assets/8d6f09de-c014-4077-8e29-a4ab5fe4ba83

**Comment by madfcat** [comment]
> only relevant difference I can think of between your demo and my case is that one of the users was 42auth
> 
>  Screen.Recording.2024-12-20.at.16.45.01.mov

It looks so broken...

0:48 - Before the first match it shows Player 4 vs Player 3. Like the AI should play against Taavi. And as I understand the AI Player should be on the left? Can we even have AI on left side?
Then second match is shown as Player 2 vs Player 1.
On the left side we see that:
Player 1 - asdf
Player 2 - ffff
Player 3 - Taavi Oramo
Player 4 - AI Player

1:00 - After the first match. Now the bracket shows Player 1 vs PLayer 2 for the first match??? Player 3 vs Player 4 for the second match.
Now on the left side (?????):
Player 1 - Taavi Oramo
Player 2 - AI Player
Player 3 - ffff
Player 4 - asdf

Everything is mixed now...

**Comment by dnapi** [comment]
There is some details about AI. 

AI plays only on the right side. adding AI to the left side will kind of double the about of work. If it is selected on the left side it will be moved to the right causing the mess with the numbering players. But data stored in the backend correctly, no shoild be no mess there. The mess in numbering can be avoided by not allowing to select AI on the left side  or implementing AI on the left or by considering it is as a feature.  At this moment some work was already done to make it as a feature. 

you can not win AI in with current settings. we need to switch on ball acceleration and weaken AI. With ball acceleration if 1 sec for decision making is enough you may try to bit AI.  We was considering to make customization with option than would make AI weaker by reducing the speed of its racket.  But probably we will not have customization.

I fix the problem with AI at first second in apimikov/gamestart

**Comment by dnapi** [comment]
to switch on acceleration change `const ballAccelerationCoef = 1.0  // 1.5`  in main.js

**Comment by taoramo** [comment]
The weirdness of users getting shifted around doesn't appear anymore but the AI still stops playing at all. Again, to replicate toramo/testing branch should be used (it's up to date with master and is therefore the closest to submission). 

Log in 2 players normally
third player using oauth
4th player normally
log out 4th player

Now AI refuses to play anywhere.
