### ISSUE TITLE
Controls acting weird + Tournament Avatars + Not empty tournament name input field

### ISSUE THREAD

**Issue by madfcat** [DaveeHorvath/ascension#87]
- The controls are acting weird when I spam the buttons (W, S). Sometimes not responding, sometimes it is like the button was held. Maybe it is just my laptop dying. Needs additional check.
- The avatar acting weird for AI in Tournament. At first, it is AI avatar. After the first match it becomes the fallback avatar.
- Avatars not shown for the players, always fallback is shown.
- Player1, Player2, Player3, Player4 can be substituted to the displayNames/usernames.
- Tournament name field should be emptied.

https://github.com/user-attachments/assets/018b5f60-8258-4072-91f1-91fa128457b0

**Comment by nikkxll** [comment]
everything should be fixed by now at master. 
Please, consider closing the issue
