### ISSUE TITLE
AI vs AI when creating tournament.

### ISSUE THREAD

**Issue by madfcat** [DaveeHorvath/ascension#92]
Creating a tournament leads to AI vs AI. I do not know why.

https://github.com/user-attachments/assets/fad92d8d-995b-4115-a493-e6a6d324bd3b

**Comment by carter212-star** [comment]
Hi @DaveeHorvath 
I happened to visit your profile on LinkedIn.
Are you interested in training AI models?
Let us discuss about how to build our business.
Contact me here or at discord.
Send me friend request and I will accept.
My discord name is :
dancarter_30880
