### ISSUE TITLE
42auth player breaks AI

### ISSUE THREAD

**Issue by taoramo** [DaveeHorvath/ascension#98]
This replaces the old issue which was way too complicated.

To replicate use toramo/testing branch (it's up to date with master and therefore the closest to submission). 

Log in using 42auth
Start 1v1 game with ai
AI breaks and doesn't play in any case anymore.

No clue what's going on.

**Comment by dnapi** [comment]
which of the branches should be tested? I have tried master. I can't login with 42 .

**Comment by taoramo** [comment]
Currently toramo/testing. There's a pr open to merge it.

**Comment by dnapi** [comment]
![image](https://github.com/user-attachments/assets/1892b234-c612-4ee2-802e-e99708a0d662)
I can't confirm the  issue . Everything work as expected.

**Comment by taoramo** [comment]
For me AI doesn't move at all. Does it for you? I'll start from scratch
again to see if I'm insane.

**Comment by taoramo** [comment]
I've been testing with both Zen browser and Chrome, seems like behaviour of ai is erratic on the zen browser. On chrome this issue doesn't exist. So I guess we just don't support Zen.

**Comment by dnapi** [comment]
I used chrome.
